Release of Ground Station V1.0
THI-Drone/Ground_Station pull request #2
Opened 2024-04-25 19:57 UTC by di-math

Diese Version der Ground-Station-Webapp ist ein Kandidat für eine V1.0 - sie erfüllt alle grundlegenden Mindestanforderungen: connecten auf einen UNIX-Socket, CLI-like Ausgabe im Browser, simples hosting als Docker-Container.

Haben wir konkrete Anforderungen an Testing? Ich hatte mal mit irgendjemandem aus V&V, wsl. Petros gesprochen, der meinte weil nicht Mission Critical, machen wir kein Testing. 

Wie seht ihr das? Bitte um Feedback.

2024-04-26 13:38 UTC, J0hn-Lawrence requested changes
See comments, overall looking quite good :)

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +This is the Ground-Station-Web-App intendet to be used together with the Ground-Station-ROS-Node. This webapp connects to the Ground-Station-ROS-Node via a UNIX socket. Webclients can access a webpag
typo, "intendet" should be "intended" instead

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +This Ground-Station-Web-App serves drone-telemetry-logs to make them accessible for flighttest-crews in their own device's browsers. The backend is implemented using _Node.js_, while the frontend is
typo again, "intented" should be "intended"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +This Ground-Station-Web-App serves drone-telemetry-logs to make them accessible for flighttest-crews in their own device's browsers. The backend is implemented using _Node.js_, while the frontend is
typo, "form" should be "from"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +This Ground-Station-Web-App serves drone-telemetry-logs to make them accessible for flighttest-crews in their own device's browsers. The backend is implemented using _Node.js_, while the frontend is
typo, "seperatly" should be "separately"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +This Ground-Station-Web-App serves drone-telemetry-logs to make them accessible for flighttest-crews in their own device's browsers. The backend is implemented using _Node.js_, while the frontend is
typo, "Preferable" should be "Preferably"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +This Ground-Station-Web-App serves drone-telemetry-logs to make them accessible for flighttest-crews in their own device's browsers. The backend is implemented using _Node.js_, while the frontend is
typo, "countainer" should be "container".

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +After [installing](#installation) the Web-App clients can access the Web-App through the host. When accessing the site, the client-app connects to the backend's websocket and from there off receives
typo, "installing" should be "installation"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +After [installing](#installation) the Web-App clients can access the Web-App through the host. When accessing the site, the client-app connects to the backend's websocket and from there off receives
typo, "send" should be "sent"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +If the log-messages overflow the available space in the browser, the user can scroll throught the messages. When scrolling all the way down, the scroll logs onto the newest received message (from the
typo, "scroll trought" should be "scroll through"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +If the log-messages overflow the available space in the browser, the user can scroll throught the messages. When scrolling all the way down, the scroll logs onto the newest received message (from the
grammar, "from there off" should be "from there on"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +```
please add language type declaration ( -> bash) to this code block

2024-04-26 13:38 UTC, J0hn-Lawrence commented on README.md
> +The back-end environment-variables can be set either throght the file located under web/backend/.env or using any other ways for setting environment-variables in the final Web-App's container.
typo, "throght" should be "through"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on test/test_unix_socket/receiver.py
> +The goal of this script is to connect to an existing UNIX-socket an listen for everything.
typo "an" should be "and"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on test/test_unix_socket/sender.py
> +    Checks rather if a socket-file already exists on the given path.
what should "rather" mean in this context?

2024-04-26 13:38 UTC, J0hn-Lawrence commented on test/test_unix_socket/sender.py
> +    Defines the message block to be continuosly send.
typo, "send" should be "sent"

2024-04-26 13:38 UTC, J0hn-Lawrence commented on test/test_unix_socket/sender.py
> +def run_dummy_server(socket_path=DEFAULT_UNIX_SOCKET_PATH):
function missing docstring

2024-04-27 12:59 UTC, maf0115 approved these changes

2024-04-27 13:08 UTC, MatixLoc commented
> Diese Version der Ground-Station-Webapp ist ein Kandidat für eine V1.0 - sie erfüllt alle grundlegenden Mindestanforderungen: connecten auf einen UNIX-Socket, CLI-like Ausgabe im Browser, simples hosting als Docker-Container.
> 
> Haben wir konkrete Anforderungen an Testing? Ich hatte mal mit irgendjemandem aus V&V, wsl. Petros gesprochen, der meinte weil nicht Mission Critical, machen wir kein Testing.
> 
> Wie seht ihr das? Bitte um Feedback.

Ja wir haben dafür keine Testing Strategie, da es kein kritisches System ist. Natürlich dürfen dennoch gerne Tests geschreiben werden. 

Theoretisch können wir auch den workflow hier einbinden.

2024-04-27 13:09 UTC, MatixLoc requested changes
Bitte ändere den main branch zu release und passe diesen PR dann an, dass er auf release zeigt.

2024-04-28 15:26 UTC, di-math commented on README.md
> +This is the Ground-Station-Web-App intendet to be used together with the Ground-Station-ROS-Node. This webapp connects to the Ground-Station-ROS-Node via a UNIX socket. Webclients can access a webpag
See 08812c9

2024-04-28 15:26 UTC, di-math commented on README.md
> +This Ground-Station-Web-App serves drone-telemetry-logs to make them accessible for flighttest-crews in their own device's browsers. The backend is implemented using _Node.js_, while the frontend is
See 08812c9

2024-04-28 15:26 UTC, di-math commented on README.md
> +After [installing](#installation) the Web-App clients can access the Web-App through the host. When accessing the site, the client-app connects to the backend's websocket and from there off receives
See 08812c9

2024-04-28 15:26 UTC, di-math commented on README.md
> +If the log-messages overflow the available space in the browser, the user can scroll throught the messages. When scrolling all the way down, the scroll logs onto the newest received message (from the
See 08812c9

2024-04-28 15:26 UTC, di-math commented on README.md
> +The back-end environment-variables can be set either throght the file located under web/backend/.env or using any other ways for setting environment-variables in the final Web-App's container.
See 08812c9

2024-04-28 15:26 UTC, di-math commented on test/test_unix_socket/sender.py
> +    Checks rather if a socket-file already exists on the given path.
See 08812c9

2024-04-28 15:26 UTC, di-math commented on test/test_unix_socket/sender.py
> +def run_dummy_server(socket_path=DEFAULT_UNIX_SOCKET_PATH):
See 08812c9

2024-04-28 15:27 UTC, di-math commented on README.md
> +```
See 08812c9

2024-04-28 15:27 UTC, di-math commented on test/test_unix_socket/receiver.py
> +The goal of this script is to connect to an existing UNIX-socket an listen for everything.
See 08812c9

2024-04-28 15:27 UTC, di-math commented on test/test_unix_socket/sender.py
> +    Defines the message block to be continuosly send.
See 08812c9

2024-04-28 15:30 UTC, di-math commented
> > Diese Version der Ground-Station-Webapp ist ein Kandidat für eine V1.0 - sie erfüllt alle grundlegenden Mindestanforderungen: connecten auf einen UNIX-Socket, CLI-like Ausgabe im Browser, simples hosting als Docker-Container.
> > Haben wir konkrete Anforderungen an Testing? Ich hatte mal mit irgendjemandem aus V&V, wsl. Petros gesprochen, der meinte weil nicht Mission Critical, machen wir kein Testing.
> > Wie seht ihr das? Bitte um Feedback.
> 
> Ja wir haben dafür keine Testing Strategie, da es kein kritisches System ist. Natürlich dürfen dennoch gerne Tests geschreiben werden.
> 
> Theoretisch können wir auch den workflow hier einbinden.

@MatixLoc, alright - dann würde ich das als mögliche Arbeit noch im Hinterkopf behalten. Wenn die Tests für dich jetzt aber nicht zwangsläufig sind, würde ich sie zunächst weglassen und einen ersten Release priorisieren.

2024-04-28 16:30 UTC, MatixLoc approved these changes

2024-04-30 14:16 UTC, J0hn-Lawrence approved these changes

2024-04-30 14:17 UTC, merged